spring: 
    profiles: 
        active: 
        - dev
---
spring: 
    profiles: dev
    application: 
        name: microservicecloud-config-hanjia-dev
---
spring: 
    profiles: test
    application: 
        name: microservicecloud-config-hanjia-test